addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"           % "3.9.21")
addSbtPlugin("com.github.sbt"            % "sbt-pgp"                % "2.2.1")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"           % "0.11.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"           % "2.5.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"          % "2.0.8")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"           % "0.4.2")
addSbtPlugin("com.github.sbt"            % "sbt-release"            % "1.1.0")
addSbtPlugin("org.jmotor.sbt"            % "sbt-dependency-updates" % "1.2.7")
